In [ ]:
import pandas as pd
data={
    "name":["ram","sam","tom"],
    "city":["mumabi","hyd","delhi"]

}
df=pd.DataFrame(data)
print(df)

  name    city
0  ram  mumabi
1  sam     hyd
2  tom   delhi


In [ ]:
# Label encoding
import pandas as pd
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["city_encoded"]=le.fit_transform(df["city"])
print(df)

  name    city  city_encoded
0  ram  mumabi             2
1  sam     hyd             1
2  tom   delhi             0


In [ ]:
#one hot encoding
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoded=encoder.fit_transform(df[["city"]])
print(encoded.toarray())

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

encoded = encoder.fit_transform(df[["city"]])

encoded_df = pd.DataFrame(
    encoded,
    columns=encoder.get_feature_names_out(["city"])
)

df = pd.concat([df, encoded_df], axis=1)

print(df)

  name    city  city_encoded  city_delhi  city_hyd  city_mumabi
0  ram  mumabi             2         0.0       0.0          1.0
1  sam     hyd             1         0.0       1.0          0.0
2  tom   delhi             0         1.0       0.0          0.0


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "City": ["Mumbai", "Delhi", "Hyderabad", "Mumbai", "Delhi"],
    "Education": ["Bachelor", "Master", "PhD", "Bachelor", "Master"]
})

print(df)

        City Education
0     Mumbai  Bachelor
1      Delhi    Master
2  Hyderabad       PhD
3     Mumbai  Bachelor
4      Delhi    Master


In [ ]:
#ordinal encoding
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder
Oe=OrdinalEncoder()
df["Education_order"]=Oe.fit_transform(df[["Education"]])
print(df)

        City Education  city_encoded  Education_order
0     Mumbai  Bachelor           2.0              0.0
1      Delhi    Master           0.0              1.0
2  Hyderabad       PhD           1.0              2.0
3     Mumbai  Bachelor           2.0              0.0
4      Delhi    Master           0.0              1.0


In [ ]:
#feature encoding
freq = df["City"].value_counts()

df["City_frequency"] = df["City"].map(freq)

print(df)

        City Education  city_encoded  Education_order  City_frequency
0     Mumbai  Bachelor           2.0              0.0               2
1      Delhi    Master           0.0              1.0               2
2  Hyderabad       PhD           1.0              2.0               1
3     Mumbai  Bachelor           2.0              0.0               2
4      Delhi    Master           0.0              1.0               2


In [ ]:
#Target encoding
from sklearn.preprocessing import TargetEncoder
y=[1,0,1,1,0]
encoder=TargetEncoder(cv=2)
encoded=encoder.fit_transform(df[["City"]],y)
print(encoded)


[[1. ]
 [0. ]
 [0.5]
 [1. ]
 [0. ]]


In [ ]:
import pandas as pd
data={
    "name":["ram","sam","tom","raju"],
    "salary":[100000,200000,300000,400000]

}
df=pd.DataFrame(data)
print(df)


   name  salary
0   ram  100000
1   sam  200000
2   tom  300000
3  raju  400000


In [ ]:
#standard Scaler
import pandas as pd
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
df["salary"]=scaler.fit_transform(df[["salary"]])
print(df)

   name    salary
0   ram -1.341641
1   sam -0.447214
2   tom  0.447214
3  raju  1.341641


In [ ]:
#Normalisattion MinMaxscaler
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
df["salary"]=scaler.fit_transform(df[["salary"]])
print(df)

   name    salary
0   ram  0.000000
1   sam  0.333333
2   tom  0.666667
3  raju  1.000000


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Age": [12, 18, 25, 35, 45, 60, 75]
})

print(df)

   Age
0   12
1   18
2   25
3   35
4   45
5   60
6   75


In [ ]:
df["Age_Group"] = pd.cut(
    df["Age"],
    bins=[0, 18, 35, 60, 100],
    labels=["Child", "Young", "Adult", "Senior"]
)

print(df)

   Age Age_Group
0   12     Child
1   18     Child
2   25     Young
3   35     Young
4   45     Adult
5   60     Adult
6   75    Senior


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Date": [
        "2025-01-15",
        "2025-03-20",
        "2025-06-10"
    ]
})

print(df)

         Date
0  2025-01-15
1  2025-03-20
2  2025-06-10


In [ ]:
import pandas as pd
df["Date"]=pd.to_datetime(df["Date"])
df["year"]=df["Date"].dt.year
df["month"]=df["Date"].dt.month
df["day"]=df["Date"].dt.day
print(df)

        Date  year  month  day
0 2025-01-15  2025      1   15
1 2025-03-20  2025      3   20
2 2025-06-10  2025      6   10


In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Salary": [10000, 15000, 20000, 50000, 1000000]
})

print(df)

    Salary
0    10000
1    15000
2    20000
3    50000
4  1000000


In [ ]:
import numpy as np

df["Log_Value"] = np.log(df["Salary"])
print(df)

    Salary  Log_Value
0    10000   9.210340
1    15000   9.615805
2    20000   9.903488
3    50000  10.819778
4  1000000  13.815511


In [ ]:
data={
    "name":["ram","sam","tom","raju"],
    "salary":[100000,200000,300000,1000000]

}
df=pd.DataFrame(data)
print(df)

   name   salary
0   ram   100000
1   sam   200000
2   tom   300000
3  raju  1000000


In [ ]:
#handling outliers using IQR method
import pandas as pd
q1=df["salary"].quantile(0.25)
q3=df["salary"].quantile(0.75)
IQR=q3-q1
lower=q1-1.5*IQR
upper=q3+1.5* IQR
outliers=df[(df["salary"]<lower)|(df["salary"]>upper)]
print(outliers)

   name   salary
3  raju  1000000


In [ ]:
df["salary"]=df["salary"].clip(lower,upper)
print(df)


   name  salary
0   ram  100000
1   sam  200000
2   tom  300000
3  raju  925000


In [ ]:
import numpy as np
df["salary"]=np.log(df["salary"])
print(df)

   name    salary
0   ram  2.443470
1   sam  2.501934
2   tom  2.534612
3  raju  2.620133


In [ ]:
import pandas as pd
data={
    "name":["ram","sam","tom"],
    "income":[1000,2000,400000]
}
df=pd.DataFrame(data)
print(df)

  name  income
0  ram    1000
1  sam    2000
2  tom  400000


In [ ]:
from scipy.stats import boxcox
df["income"],_=boxcox(df["income"])
print(df)

  name    income
0  ram  2.788480
1  sam  2.857122
2  tom  3.083312


In [ ]:
from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method="yeo-johnson")
df["income"] = pt.fit_transform(df[["income"]])
print(df)

  name    income
0  ram -1.193752
1  sam -0.059795
2  tom  1.253547
